### Endpoint de teste
GET http://localhost:3003/ping

###

POST http://localhost:3003/studant
Content-Type: application/json

{   
    "name":"Dany",
    "email": "danyBy@gmail.com",
    "data_nasc":"20/09/1983", 
    "gang_id":"1",
    "hobbies":["festa","amigos"]
   
}

###

POST http://localhost:3003/teacher
Content-Type: application/json

{   
    "name":"Junior",
    "email": "junior@labenu.com",
    "data_nasc":"05/07/1988", 
    "gang_id":"1"
}

###

POST http://localhost:3003/gang
Content-Type: application/json

{
    "gang_name": "Turma Barros",
    "modulo_atual": "1"
}

###

PUT http://localhost:3003/students
Content-Type: application/json

{
    "id": "1",
    "gangid":"1672081244316"
}

###

GET http://localhost:3003/studant
Content-Type: application/json

{
    "name":"Dany"
}

###

GET http://localhost:3003/teacher
Content-Type: application/json

{
    "name":"Fay"
}

