POST http://localhost:3003/studant
Content-Type: application/json

{   
    "name":"Bianca",
    "email": "bianca@gmail.com",
    "data_nasc":"20/09/1983", 
    "gang_id":"1",
    "hobbies":[
        {"name":"PESCAR"},
        {"name":"jogar bola"},
        {"name":"caminhar"}
    ]
   
}